version: v1

build:
  # Image used by CI pipelines in build tasks, recommendation: use the bitnami dotnet repo if you want to change runtime version: https://hub.docker.com/r/bitnami/dotnet-sdk
  image: mcr.microsoft.com/dotnet/sdk:7.0

  # definitions of environment variables that will be used in all stages of your pipeline
  environmentVariables: []
    #- key: variable1
    #  value: value1
    #- key: variable2
    #  value: value2
    #- key: variable3
    #  value: value3
  pipelines:
    release:
      pipeline: dotnet-nuget-lib